import type { ExtensionCommandContext, ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { clearBaselines, latestBaseline, type DcpRuntime } from "../runtime.ts";
import { createEnvelope, OPERATION_CUSTOM_TYPE } from "../state/operations.ts";
import { reduceEnvelope } from "../state/reducer.ts";
import { hashJson } from "../util/hash.ts";
export async function activationCommand(args: string, active: boolean, ctx: ExtensionCommandContext, pi: ExtensionAPI, runtime: DcpRuntime): Promise<void> { const available = orderedBlocks(runtime).filter((block) => block.available && (active ? block.userDecompressed : block.active)); if (!args.trim()) { ctx.ui.notify(`${active ? "Eligible recompression" : "Active"} blocks: ${available.map((block, index) => `${aliasFor(runtime, block.blockId) || `b${String(index + 1).padStart(4, "0")}`}:${block.topic}`).join(", ") || "none"}`, "info"); return; } const target = resolveTarget(args.trim(), available, runtime); if (!target) { ctx.ui.notify("Unknown block target. Refresh /dcp context and use a current block number or bNNNN.", "error"); return; } await runtime.mutex.runExclusive(() => { const envelope = createEnvelope({ type: "blocks.activation.changed", blockIds: [target.blockId], active, cause: active ? "user-recompress" : "user-decompress" }, runtime.sessionId, "0.2.0", hashJson([runtime.sessionId, active ? "recompress" : "decompress", target.blockId])); pi.appendEntry(OPERATION_CUSTOM_TYPE, envelope); runtime.reduced = reduceEnvelope(runtime.reduced, envelope); runtime.generation++; clearBaselines(runtime); }); ctx.ui.notify(`pi-dcp ${active ? "recompressed" : "decompressed"} ${target.topic}.`, "info"); }
function orderedBlocks(runtime: DcpRuntime) { const aliases = new Map([...latestBaseline(runtime)?.blockAliases.values() || []].map((item) => [item.blockId, Number(item.alias.slice(1))])); return [...runtime.reduced.blocks.values()].sort((a, b) => (aliases.get(a.blockId) ?? Number.MAX_SAFE_INTEGER) - (aliases.get(b.blockId) ?? Number.MAX_SAFE_INTEGER) || a.blockId.localeCompare(b.blockId)); }
function aliasFor(runtime: DcpRuntime, blockId: string): string | undefined { return [...latestBaseline(runtime)?.blockAliases.values() || []].find((item) => item.blockId === blockId)?.alias; }
function resolveTarget(value: string, blocks: readonly { blockId: string; topic: string }[], runtime: DcpRuntime): { blockId: string; topic: string } | undefined { if (/^b\d{4}$/.test(value)) { const aliasNumber = Number(value.slice(1)); return blocks.find((block) => Number(aliasFor(runtime, block.blockId)?.slice(1)) === aliasNumber) || blocks[aliasNumber - 1]; } const index = Number(value); return Number.isInteger(index) && index >= 1 ? blocks[index - 1] : undefined; }
