import type { ExtensionCommandContext, ExtensionAPI } from "@earendil-works/pi-coding-agent";
import type { CanonicalIndex } from "../identity/types.ts";
import type { DcpRuntime } from "../runtime.ts";
import { projectContextEntries } from "../identity/project.ts";
import { buildProtocolUnits } from "../identity/protocol.ts";
import { collectToolRecords } from "../strategies/deduplicate.ts";
import { isProtectedTool } from "../compression/protected.ts";
import { createEnvelope, OPERATION_CUSTOM_TYPE, type PrunedToolDecision } from "../state/operations.ts";
import { reduceEnvelope } from "../state/reducer.ts";
import { hashJson } from "../util/hash.ts";
import { persistSavingsBestEffort } from "../stats.ts";
import { clearBaselines } from "../runtime.ts";
export async function sweepCommand(args: string, ctx: ExtensionCommandContext, pi: ExtensionAPI, runtime: DcpRuntime): Promise<void> { const raw = args.trim(); if (raw && (!/^\d+$/.test(raw) || Number(raw) < 1)) { ctx.ui.notify("Usage: /dcp sweep [positive integer]", "error"); return; } const limit = raw ? Number(raw) : undefined; await runtime.mutex.runExclusive(async () => { const projection = projectContextEntries(ctx.sessionManager.buildContextEntries()); if (!projection.ok) return; const index = buildProtocolUnits(projection.messages); if (!("units" in index)) return; const latestUser = [...index.units].map((unit, i) => unit.role === "user" ? i : -1).filter((i) => i >= 0).at(-1) ?? -1; const records = collectToolRecords(index).filter((record) => record.unitIndex > latestUser && record.result && !record.result.isError && !isProtectedTool(record.name, record.args, { cwd: ctx.cwd, protectedTools: runtime.config.commands.protectedTools, protectedFilePatterns: runtime.config.protectedFilePatterns })); const selected = (limit === undefined ? records : records.slice(-limit)); const decisions: PrunedToolDecision[] = selected.filter((record) => !runtime.reduced.toolPrunes.get(record.toolCallId)?.output).map((record) => ({ toolCallId: record.toolCallId, kind: "sweep-output", estimatedTokens: Math.max(1, Math.ceil(JSON.stringify(record.result?.content || []).length / 4)) })); if (!decisions.length) { ctx.ui.notify("pi-dcp sweep found no eligible completed tools.", "info"); return; } const envelope = createEnvelope({ type: "tools.pruned", decisions: decisions }, runtime.sessionId, "0.2.0", hashJson([runtime.sessionId, "sweep", decisions])); pi.appendEntry(OPERATION_CUSTOM_TYPE, envelope); await persistSavingsBestEffort(envelope, runtime.logger); runtime.reduced = reduceEnvelope(runtime.reduced, envelope); runtime.generation++; clearBaselines(runtime); ctx.ui.notify(`pi-dcp swept ${decisions.length} tool output(s).`, "info"); }); }
