import type { AgentMessage } from "@earendil-works/pi-agent-core";
import { canonicalJson, canonicalPlainObject } from "../util/canonical-json.ts";
import { isProtectedTool, type ProtectionOptions } from "../compression/protected.ts";
import type { CanonicalIndex } from "../identity/types.ts";
import type { PrunedToolDecision } from "../state/operations.ts";
export interface ToolRecord { toolCallId: string; name: string; args: unknown; unitIndex: number; result?: Extract<AgentMessage, { role: "toolResult" }>; call: Extract<AgentMessage, { role: "assistant" }>; }
export function collectToolRecords(index: CanonicalIndex): ToolRecord[] { const byKey = new Map(index.entries.map((item) => [`${item.key.entryId}:${item.key.projection}`, item])); const records: ToolRecord[] = []; for (let unitIndex = 0; unitIndex < index.units.length; unitIndex++) { const unit = index.units[unitIndex]; const projected = unit.messageKeys.map((key) => byKey.get(`${key.entryId}:${key.projection}`)).filter((item): item is NonNullable<typeof item> => item !== undefined); const assistant = projected.find((item) => item.message.role === "assistant")?.message; if (!assistant || assistant.role !== "assistant") continue; const results = new Map(projected.filter((item): item is typeof item & { message: Extract<AgentMessage, { role: "toolResult" }> } => item.message.role === "toolResult").map((item) => [item.message.toolCallId, item.message])); for (const part of assistant.content) if (part.type === "toolCall") records.push({ toolCallId: part.id, name: part.name, args: part.arguments, unitIndex, result: results.get(part.id), call: assistant }); } return records; }
export function deduplicate(index: CanonicalIndex, options: ProtectionOptions & { turnProtection?: { enabled: boolean; turns: number } }): PrunedToolDecision[] { const records = collectToolRecords(index).filter((record) => record.result && !record.result.isError && !isProtectedTool(record.name, record.args, options) && !isRecent(record.unitIndex, index, options.turnProtection)); const newest = new Map<string, ToolRecord>(); const decisions: PrunedToolDecision[] = []; for (const record of records) { let key: string; try { key = `${record.name}\0${canonicalJson(canonicalPlainObject(record.args))}`; } catch { continue; } newest.set(key, record); } for (const record of records) { let key: string; try { key = `${record.name}\0${canonicalJson(canonicalPlainObject(record.args))}`; } catch { continue; } if (newest.get(key)?.toolCallId !== record.toolCallId) decisions.push({ toolCallId: record.toolCallId, kind: "dedup-output", estimatedTokens: estimate(record.result) }); } return decisions; }
function isRecent(unitIndex: number, index: CanonicalIndex, protection?: { enabled: boolean; turns: number }): boolean { if (!protection?.enabled) return false; const users = index.units.map((unit, i) => unit.role === "user" ? i : -1).filter((i) => i >= 0); const newest = users.at(-1) ?? -1; const oldestProtected = users[Math.max(0, users.length - protection.turns)] ?? newest + 1; return unitIndex >= oldestProtected && unitIndex <= newest; }
function estimate(message: AgentMessage | undefined): number { if (!message || message.role !== "toolResult") return 0; return Math.max(1, Math.ceil(JSON.stringify(message.content).length / 4)); }
